### ISSUE TITLE
Exception when selecting document

### ISSUE THREAD

**Issue by jimbosimo** [Kanatoko/MonjaDB#1]
Hi,

great tool!

Info about my set up:

MonjaDB Version:  1.0.3.201208131615
Eclipse Version: 4.2.0
Build id: I20120608-1400
OS: Windows 7 64-bit

I get the following exception when selecting a document with custom '_id' key.

Fri Sep 14 14:25:01 CEST 2012:(MDocumentList.java:711)::DEBUG::test
Fri Sep 14 14:25:01 CEST 2012:(MActionManager.java:59)::DEBUG::mj edit 455beaf1-19ab-41f3-8298-9f611b973afd
Fri Sep 14 14:25:01 CEST 2012:(MActionManager.java:107)::DEBUG::net.jumperz.app.MMonjaDBCore.action.mj.MEditAction@594be58d
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::[
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::net.jumperz.app.MMonjaDBCore.action.MParseException: Parse Error : mj edit 455beaf1-19ab-41f3-8298-9f611b973afd
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at net.jumperz.app.MMonjaDBCore.action.MActionManager.executeAction(MActionManager.java:108)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at net.jumperz.app.MMonjaDB.eclipse.view.MAbstractView.executeAction(MAbstractView.java:63)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at net.jumperz.app.MMonjaDB.eclipse.view.MDocumentList.onTableSelect(MDocumentList.java:684)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at net.jumperz.app.MMonjaDB.eclipse.view.MDocumentList.handleEvent2(MDocumentList.java:948)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at net.jumperz.app.MMonjaDB.eclipse.view.MAbstractView.handleEvent(MAbstractView.java:165)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1022)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:916)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:585)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:540)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at java.lang.reflect.Method.invoke(Unknown Source)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::]
Fri Sep 14 14:25:01 CEST 2012:(MStdoutView.java:37)::DEBUG::net.jumperz.app.MMonjaDBCore.action.MParseException: Parse Error : mj edit 455beaf1-19ab-41f3-8298-9f611b973afd
Fri Sep 14 14:25:01 CEST 2012:(MDocumentList.java:711)::DEBUG::test

I'm generating documents with Java driver 2.8.0.
The key that is causing trouble is of type java.lang.String, I'm not using ObjectId.

I'm available for testing and any questions that might help you.

Really great tool!

Regards,
Drazen

**Comment by Kanatoko** [comment]
Give me some days.

**Comment by Kanatoko** [comment]
Maybe fixed on 1.0.4. Thank you for your feedback.
