### ISSUE TITLE
DocumentEditor empty and cannot update, remove and so on

### ISSUE THREAD

**Issue by sbrauns** [Kanatoko/MonjaDB#10]
Hi, 

I have multiple problems with MonjaDB Plugin (version  MonjaDBFeature   1.0.9.201305031625  net.jumperz.app.MMonjaDB.feature.group  JUMPERZ.NET):

I have created a collection named: 
collectionAV_urn:uuid:WP_L/W/P1/_Vw

 (Please note that there are many special characters in it!)

The document list works fine and shows all documents. 
One example document:
{
    "_id" : NumberLong("1368544353880"),
    "v" : 5000000,
    "q" : 0,
    "difMS" : NumberLong(0)
}

First Bug:
If I click on a document DocumentEditor stays empty (no error appears in MonjaDB Log console).

Second Bug:
When I now try to change a document field or try to remove the document following appears in console:

Tue May 14 19:33:35 CEST 2013:(MActionManager.java:59)::DEBUG::db.collectionAV_urn:uuid:WP_L/W/P1/_Vw.update({ "_id" : NumberLong("1368544353880") },{ "$set" : { "v" : 1 } },false, false )
Tue May 14 19:33:35 CEST 2013:(MActionManager.java:59)::DEBUG::db.collectionAV_urn:uuid:WP_L/W/P1/_Vw.find()
Tue May 14 19:33:35 CEST 2013:(MActionManager.java:59)::DEBUG::mj edit 0
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:28)::DEBUG::Thread[Thread-9,6,main]:event_update_start
Tue May 14 19:33:35 CEST 2013:(MStdoutView.java:37)::DEBUG::Thread[Thread-9,6,main]:[
Tue May 14 19:33:35 CEST 2013:(MStdoutView.java:37)::DEBUG::Thread[Thread-9,6,main]:com.mongodb.CommandResult$CommandFailure: command failed [command failed [$eval] { "serverUsed" : "localhost:27017" , "errmsg" : "compile failed: JS Error: SyntaxError: missing ; before statement nofile_a:0" , "ok" : 0.0}
Tue May 14 19:33:35 CEST 2013:(MStdoutView.java:37)::DEBUG::Thread[Thread-9,6,main]:    at com.mongodb.CommandResult.getException(CommandResult.java:75)
Tue May 14 19:33:35 CEST 2013:(MStdoutView.java:37)::DEBUG::Thread[Thread-9,6,main]:    at com.mongodb.CommandResult.throwOnError(CommandResult.java:121)
Tue May 14 19:33:35 CEST 2013:(MStdoutView.java:37)::DEBUG::Thread[Thread-9,6,main]:    at com.mongodb.DB.eval(DB.java:242)
Tue May 14 19:33:35 CEST 2013:(MStdoutView.java:37)::DEBUG::Thread[Thread-9,6,main]:    at net.jumperz.app.MMonjaDBCore.action.MUpdateAction.executeFunction(MUpdateAction.java:63)
Tue May 14 19:33:35 CEST 2013:(MStdoutView.java:37)::DEBUG::Thread[Thread-9,6,main]:    at net.jumperz.app.MMonjaDBCore.action.MAbstractAction.execute(MAbstractAction.java:52)
Tue May 14 19:33:35 CEST 2013:(MStdoutView.java:37)::DEBUG::Thread[Thread-9,6,main]:    at net.jumperz.util.MWorkerThread.run(MWorkerThread.java:59)
Tue May 14 19:33:35 CEST 2013:(MStdoutView.java:37)::DEBUG::Thread[Thread-9,6,main]:]
Tue May 14 19:33:35 CEST 2013:(MStdoutView.java:37)::DEBUG::Thread[Thread-9,6,main]:com.mongodb.CommandResult$CommandFailure: command failed [command failed [$eval] { "serverUsed" : "localhost:27017" , "errmsg" : "compile failed: JS Error: SyntaxError: missing ; before statement nofile_a:0" , "ok" : 0.0}
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:28)::DEBUG::Thread[Thread-9,6,main]:event_error
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:33)::DEBUG::Thread[Thread-9,6,main]:[
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:33)::DEBUG::Thread[Thread-9,6,main]:com.mongodb.CommandResult$CommandFailure: command failed [command failed [$eval] { "serverUsed" : "localhost:27017" , "errmsg" : "compile failed: JS Error: SyntaxError: missing ; before statement nofile_a:0" , "ok" : 0.0}
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:33)::DEBUG::Thread[Thread-9,6,main]:   at com.mongodb.CommandResult.getException(CommandResult.java:75)
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:33)::DEBUG::Thread[Thread-9,6,main]:   at com.mongodb.CommandResult.throwOnError(CommandResult.java:121)
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:33)::DEBUG::Thread[Thread-9,6,main]:   at com.mongodb.DB.eval(DB.java:242)
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:33)::DEBUG::Thread[Thread-9,6,main]:   at net.jumperz.app.MMonjaDBCore.action.MUpdateAction.executeFunction(MUpdateAction.java:63)
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:33)::DEBUG::Thread[Thread-9,6,main]:   at net.jumperz.app.MMonjaDBCore.action.MAbstractAction.execute(MAbstractAction.java:52)
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:33)::DEBUG::Thread[Thread-9,6,main]:   at net.jumperz.util.MWorkerThread.run(MWorkerThread.java:59)
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:33)::DEBUG::Thread[Thread-9,6,main]:]
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:33)::DEBUG::Thread[Thread-9,6,main]:com.mongodb.CommandResult$CommandFailure: command failed [command failed [$eval] { "serverUsed" : "localhost:27017" , "errmsg" : "compile failed: JS Error: SyntaxError: missing ; before statement nofile_a:0" , "ok" : 0.0}
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:28)::DEBUG::Thread[Thread-9,6,main]:event_find_start
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:28)::DEBUG::Thread[Thread-9,6,main]:event_find_end
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:28)::DEBUG::Thread[Thread-9,6,main]:event_mj_edit_start
Tue May 14 19:33:35 CEST 2013:(MAuthManager.java:28)::DEBUG::Thread[Thread-9,6,main]:event_mj_edit_end

Maybe this is because of the special characters? 
Maybe use of square bracket notation helps? please see http://stackoverflow.com/questions/9569976/working-with-special-characters-in-a-mongo-collection 

Thanks in advance and best regards,

Steffen Brauns

**Comment by Kanatoko** [comment]
Second bug is fixed on 1.0.10

First bug is still investigated. Thanks for your report.

**Comment by sbrauns** [comment]
Hi, 

I updated to version 1.0.10. 
Update on a document now works fine but if I try to remove a document via right click -> "remove" then nearly same error as before appears in console and the document isn't removed. Maybe you should use square bracket notation always in your code (also on "find" methods etc. )?

Thx for your help and kind regards,

Steffen

**Comment by sbrauns** [comment]
Hi,

I just tried to edit a document via right click -> "Edit Document" and I got this in console:

::DEBUG::java.lang.NumberFormatException: For input string: "1368560058412"
Fri May 17 18:30:20 CEST 2013:(MAuthManager.java:33)::DEBUG::   at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
Fri May 17 18:30:20 CEST 2013:(MAuthManager.java:33)::DEBUG::   at java.lang.Integer.parseInt(Integer.java:495)
Fri May 17 18:30:20 CEST 2013:(MAuthManager.java:33)::DEBUG::   at java.lang.Integer.<init>(Integer.java:677)
Fri May 17 18:30:20 CEST 2013:(MAuthManager.java:33)::DEBUG::   at net.jumperz.app.MMonjaDBCore.MCoreUtil.getObjectIdFromString(MCoreUtil.java:29)
Fri May 17 18:30:20 CEST 2013:(MAuthManager.java:33)::DEBUG::   at net.jumperz.app.MMonjaDBCore.action.mj.MEditAction.parse(MEditAction.java:44)

Maybe this helps to fix first bug...

**Comment by Kanatoko** [comment]
Now 'remove' works.

**Comment by Kanatoko** [comment]
NumberFormatException is not fixed on 1.0.11

**Comment by Kanatoko** [comment]
Fixed. Try 1.0.12.

**Comment by sbrauns** [comment]
Hi, I just tried it with following document:
{
    "_id" : NumberLong("1369815794374"),
    "v" : 18648522000,
    "q" : 0,
    "difMS" : NumberLong(3238)
}

The Exception is gone but still nothing appears in Document Editor and JSON Editor after clicking on it and after right click -> "Edit Document"

Best regards, 

Steffen

**Comment by Kanatoko** [comment]
Oh, sorry it's my mistake. I fixed against Double _id. ( NumberLong should be fixed too )
Will be fixed in this week...

**Comment by Kanatoko** [comment]
Fixed. Try 1.0.13 :)

**Comment by sbrauns** [comment]
Thanks, it works! :)

**Comment by sbrauns** [comment]
Hi, 

I found one more issue with following document:
{ "_id" : "4cecc920-bec2-11e2-9e96-0800200c9a66", "nameList" : "b" }

Still nothing appears in Document Editor and JSON Editor after clicking on it and after right click -> "Edit Document".

Another bug?

**Comment by sbrauns** [comment]
Did you get a chance to look at my last reported issue above? It would be very kind if this would be fixed in the near future!

Thanks in advance and best regards!

**Comment by Kanatoko** [comment]
I'm sorry. Please wait for some time...

**Comment by Kanatoko** [comment]
Hello, try 1.0.14 !

**Comment by sbrauns** [comment]
Thanks a lot! It works...

**Comment by Kanatoko** [comment]
:)
