### ISSUE TITLE
Database manager

### ISSUE THREAD

**Issue by nikomakela** [Kanatoko/MonjaDB#12]
Currently I cannot have multiple databases in memory. I always need to click "connect to database" -button which remembers my last configurations,but if I have multiple databases that I'm managing, I always need to write new configs before connecting.

**Comment by Kanatoko** [comment]
Use the 'Actions' view and the 'Saved Actions' view.

For example, when you connect to localhost/test, you will see a line like below in the 'Actions' view.

connect localhost:27017/test

Right click the line and select 'Save'.
Once saved to the 'Saved Actions', you can select that item and Shift+Enter, or right click and choose 'Execute' to redo that action.

By the way, 'Saved Actions' can be used more than that.
If you always use the 'foo' collection in the 'test' database,
You can edit the 'Saved Actions' item like below.

connect localhost:27017/test
show dbs
show collections
db.foo.find()

You can see the documents in the 'foo' collections with just select the item and Shift/Enter

**Comment by sbrauns** [comment]
Hi, 

I would also appreciate if in the DB Tree window more than one "connection configurations" for MongoDBs could be saved. (I need for example one MongoDB on localhost and one on my productive server and so on.)

In my case the "saved actions" are not an option because I want to use all of my saved actions on both MongoDB's.

**Comment by nikomakela** [comment]
My use case is exactly the same as @sbrauns has. I need to view data from dev, test, qa and prod servers of 1 application.

**Comment by Kanatoko** [comment]
Do you want to connect to multiple databases at the same time?

**Comment by nikomakela** [comment]
I tried the saved actions that you suggested. They work just like you explained and I really can connect to all those databases that I want. I created a connections folder and added all those connection-actions there. Thanks for the tip!

However, the more logical way to connect to those databases would be the DB Tree tab which also has a nice UI. The tree could have another 1st level node that stores the connection to another server.

**Comment by Kanatoko** [comment]
It is design that MonjaDB allows only one connection, to avoid operation mistakes.

**Comment by sbrauns** [comment]
Hi, it is OK to allow only one connection at one time. It would only be more nice if in the DB Tree tab the configuration for each MongoDB could be stored.

**Comment by salhabc** [comment]
Hi there.

Can I connect to a db using a host name (if that's all I have .. verses having the db's ip)?
When I've tried the host name along with port, no connecting.
But there may be firewall rules in place where this db is .. am waiting to hear.
But just wanted to see if using a host name is acceptable with this fierce plugin?

Thank you,
_C
