### ISSUE TITLE
Square bracket notation doesn't work in some cases

### ISSUE THREAD

**Issue by sbrauns** [Kanatoko/MonjaDB#13]
Hi,

square bracket notation doesn't work in some cases for version 1.0.14:

for example 

db[ 'collectionName' ].find()

works fine, but 

db[ 'collectionName' ].find().sort({"_id":-1})

doesn' t work.

If I use

db.collectionName.find().sort({"_id":-1})

instead of square bracket notation it works just fine, so it must be a bug...

Thanks in advance!

**Comment by Kanatoko** [comment]
Thank you for reporting the bug. Fixed in 1.0.15.
Maybe there are more bugs around the square bracket notation...

**Comment by sbrauns** [comment]
Thanks, works fine now!
