### ISSUE TITLE
Connecting to clustered MongoDB

### ISSUE THREAD

**Issue by nikomakela** [Kanatoko/MonjaDB#15]
I'm not able to connect to MongoDB database that is configured to use replicas. My version of MonjaDB is 1.0.14 and MongoDB is 2.4.6. With a current version of MonjaDB, should it be possible to use clustered database?

**Comment by Kanatoko** [comment]
Do you mean ReplicaSets? or Sharding?

MonjaDB can connect to primary database of replica sets.

I have not tested on sharding.

**Comment by nikomakela** [comment]
I meant replica sets without sharding. But if it should work, then the problem is in my configurations. Thanks for fast reply!

**Comment by nikomakela** [comment]
I had a problem with authorization. I used dbAdmin role but it did not have enough rights to read collections data. I could get a list of collections, but could not get list of documents.

In terminal client a read-write-role is enough!

**Comment by Kanatoko** [comment]
Currently, MonjaDB does not support MongoDB2.4 with authorization.
