### ISSUE TITLE
Two rows selected in document list if first column is not id

### ISSUE THREAD

**Issue by smakela** [Kanatoko/MonjaDB#16]
If you have something else as first column than id and rows have same values in that column, two of those rows with same value is selected (as show in attached picture)

![screen shot 2013-09-23 at 3 13 34 pm](https://f.cloud.github.com/assets/865256/1191153/c6cfe2d4-2449-11e3-9ddd-565c0fd2a3ef.png)

Here's start of the object.

{
    "_class" : "OperationFormTemplate",
    "_id" : ObjectId("523fe4e43004b4e685be238d"),
}

Actions:

mj edit OperationFormTemplate

So it seems that the id column position is hard coded.

This prevents lot of the functionalities (like show row in JSON)

**Comment by smakela** [comment]
Here's the line of code that fails:

https://github.com/Kanatoko/MonjaDB/blob/master/src/net/jumperz/app/MMonjaDB/eclipse/view/MDocumentList.java#L652

**Comment by nikomakela** [comment]
I can confirm this issue. I faced the same bug in one of my collections.

**Comment by Kanatoko** [comment]
Thanks for reporting. I'll fix this in few days.

**Comment by Kanatoko** [comment]
1.0.16 is released. Maybe this issue is fixed.

I can not reproduce those issues, maybe because my environment is Ubuntu.

I added changes to codes, to always set the position of the "_id" columns to left.

Thanks you very much for your reports.

**Comment by nikomakela** [comment]
Seems like my issues are solved!

The issue was quite critical since I could not get documents' JSON nor use document editor to view the content of documents, because multiple documents (rows in editor) were selected at once. Now when _id is the first column in editor, it seems to work ok.

Thank you for your fast contribution and fix.

**Comment by smakela** [comment]
Fix seems to work!

Thanks for quick fix.
