### ISSUE TITLE
Integrate with ssh-agent if present

### ISSUE THREAD

**Issue by rmunn** [Kanatoko/MonjaDB#25]
I'm using MonjaDB on one machine while my Mongo database is on another machine I connect to via SSH. I have a passphrase on my SSH key, and I have set up ssh-agent so that I only have to type my passphrase once when I log in in the morning, and all my software that uses SSH can get my key from the ssh-agent.

All my software, that is, except for MonjaDB, which required me to type in my (quite long) passphrase a second time. This is precisely what ssh agents are designed for: it would be nice if MonjaDB was capable of integrating with them.

In case it matters, I'm running Eclipse 3.8.1 on Linux Mint 16 (which I will upgrade to Linux Mint 17 when it comes out a few days from now), and using the default SSH agent that comes with the GUI session.

**Comment by Kanatoko** [comment]
Sorry, I will not implement this issue. I think you should quit using passphrases in that case.

**Comment by paulvi** [comment]
Hello Kanatoko

Why not say, that you have no intention for the issue and live at open with saying PR are welcomed.

This way other user could learn about issue, vote for it with :+1:  and everyone see if it is really popular request.
