### ISSUE TITLE
MonjaDB update site in Eclipse Marketplace is broken 

### ISSUE THREAD

**Issue by ahoffman-xybion** [Kanatoko/MonjaDB#29]
The site used for deployment of the MonjaDB plugin within Eclipse Marketplace appears to be offline (www.jumperz.net).  Not sure if the site is just offline for maintenance or permanently, but the Eclipse plugin install is not working at the moment.

**Comment by Kanatoko** [comment]
Sorry for the inconvinience. The site is now under maintenance. It will return to online on next week.
