### ISSUE TITLE
Improvement to "Documents List" view

### ISSUE THREAD

**Issue by eyala** [Kanatoko/MonjaDB#3]
It would be great if the Documents List view, instead of making each column the same size, made each column large enough to fit the column name. Personally, I would like this as default behavior, but if it could be controlled through the preferences that would be fine too.

(I know this isn't a bug, but I didn't see how I could define this issue as improvement)

**Comment by Kanatoko** [comment]
Thank you for your feedback.

I don't think that is a good idea.
In your case, We should see both "column name size" and "data size".

For example,

{
"foo" : "long data here AAAAAAAAAAAAAAAAAAAAAAAAAA",
"long column name here BBBBBB" : "bar"
}

So, I think that each column has the same size is a good design.
