### ISSUE TITLE
Exception when selecting document with custom _id including ":"

### ISSUE THREAD

**Issue by sbrauns** [Kanatoko/MonjaDB#4]
Hi, 

I get the same Exception when selecting a document with a custom String _id as in closed issue "Exception when selecting document". Maybe it's because of the ":" in my custom id "urn:uuid:14246641-f800-4309-b9fc-f87cc6d89e1e"?

net.jumperz.app.MMonjaDBCore.action.MParseException: Parse Error : mj edit 
urn:uuid:14246641-f800-4309-b9fc-f87cc6d89e1e

Version used:  
MonjaDBFeature  1.0.6.201210061851  net.jumperz.app.MMonjaDB.feature.group  JUMPERZ.NET

Best regards,

Steffen

**Comment by Kanatoko** [comment]
Fixed in version 1.0.7.

Thank you for your feedback.

**Comment by sbrauns** [comment]
Thanks! Works...
