### ISSUE TITLE
Dead links?

### ISSUE THREAD

**Issue by kokujin** [Kanatoko/MonjaDB#5]
Hi there!

The Eclipse update and direct link to the jar produce 404's Could you check the links please? Thanks

**Comment by Kanatoko** [comment]
Thanks

Direct link is fixed. 
http://www.jumperz.net/update/plugins/net.jumperz.app.MMonjaDB_1.0.7.201301231327.jar

/update/ is still 404, but Eclipse will access to /update/site.xml etc, so that is not a problem.

**Comment by kokujin** [comment]
Hi Kanatoko,

thanks for your answer, I tried to use the update link, it started working
but stopped after a few seconds, The link to the jar file works. Can you
check this please? Thanks

**Comment by Kanatoko** [comment]
I have refreshed all contents on the Update site. Please try again.
(Direct link to the plugin jar file has changed to : http://www.jumperz.net/update/plugins/net.jumperz.app.MMonjaDB_1.0.7.201302060949.jar)
