### ISSUE TITLE
DocumentEditor empty when _id is a UUID id

### ISSUE THREAD

**Issue by phoenix741** [Kanatoko/MonjaDB#6]
Hi,

When my row have an ObjectId for the _id everything is ok (it's ok if it's a string too), but if the object _id is an UUID (created from a JAVA application), the document editor is empty.

example of document
{
    "_id" : BinData(3,"bE6SXLdg/BSQcbwDHwkxlQ=="),
    "name" : "XXXXXX",
}

I don't have exception in the console.

**Comment by Kanatoko** [comment]
Thanks for your feedback.

Fixed in 1.0.8
