### ISSUE TITLE
Actions is whitespace sensitive

### ISSUE THREAD

**Issue by aw20** [Kanatoko/MonjaDB#7]
I love this.

However when typing in a query, it is sensitive to whitespace; you can't put in carriage returns for example.

I would love to start editing this source code.

**Comment by Kanatoko** [comment]
Currently, it is design.
Each action needs to be expressed as one line.
I'll think about this...

**Comment by aw20** [comment]
Thanks for replying Kanatoko.  

As you can see, I've forked the project and have been making significant changes to it already.  Taking it more in the direction of SQLServer Workbench/MySQL Workbench tools.  Made changes to the UI and the underlying communications to Mongo.

You have done a wonderful job with this project and I am excited to have the opportunity to be extending it and taking it in a different direction.  This is the power of open source. 

Good decision to release this under a GPL license to let the community contribute.

We need to promote these tools to the Mongo community as there is a huge lack of quality of tools.  We have incorporated Mongo to our http://openbd.org/ open source Java CFML engine to great success.

**Comment by Kanatoko** [comment]
That's really great. 

Yes, I choose GPL to be freely contributed or extended for others.
Thanks for sharing your OpenBD information.
(By the way, ColdFusion is still used in Japan)
